[package]
name = "sdk"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }

async-trait = { workspace = true }
backtrace = { workspace = true }
delegate = { workspace = true }
futures = { workspace = true }
kanal = { workspace = true }
num_cpus = { workspace = true }
prometheus = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
warp = { workspace = true }
once_cell = "1.19.0"


[target.'cfg(target_os = "linux")'.dependencies]
aptos-system-utils = { workspace = true }
