[workspace]
resolver = "2"

members = ["sdk"]

[workspace.package]
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
edition = "2021"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
repository = "https://github.com/aptos-labs/aptos-indexer-processors-sdk"
rust-version = "1.75"

[workspace.dependencies]
anyhow = "1.0.86"
async-trait = "0.1.80"
futures = "0.3.30"
kanal = "0.1.0-pre8"
num_cpus = "1.16.0"
thiserror = "1.0.61"
tokio = { version = "1.37.0", features = ["full"] }
