[workspace]
resolver = "2"

members = ["sdk"]

[workspace.package]
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
edition = "2021"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
repository = "https://github.com/aptos-labs/aptos-indexer-processors-sdk"
rust-version = "1.75"

[workspace.dependencies]
anyhow = "1.0.86"

aptos-system-utils = { git = "https://github.com/aptos-labs/aptos-core.git", branch = "main" }

async-trait = "0.1.80"

backtrace = "0.3.72"

futures = "0.3.30"
kanal = "0.1.0-pre8"
num_cpus = "1.16.0"

prometheus = { version = "0.13.4", default-features = false }


thiserror = "1.0.61"
tokio = { version = "1.37.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "json"] }
warp = { version = "0.3.7", features = ["tls"] }


